- name: Add Galera template (deb)
  template:
    src: galera.cnf.j2
    dest: /etc/mysql/conf.d/galera.cnf
  vars:
    provider_path: /usr/lib/galera/libgalera_smm.so
  notify: Stop MariaDB
  when: ansible_facts['os_family'] == "Debian"
  
- name: Add Galera template (rpm)
  template:
    src: galera.cnf.j2
    dest: /etc/my.cnf.d/galera.cnf
  vars:
    provider_path: /usr/lib64/galera-4/libgalera_smm.so
  notify: Stop MariaDB
  when: ansible_facts['os_family'] == "RedHat"

- name: Flush handlers
  meta: flush_handlers

- name: Create new cluster
  command: "galera_new_cluster"
  run_once: true

- name: Start MariaDB
  systemd:
    name: mariadb
    state: started